# Generated by Django 3.1.4 on 2020-12-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
