# Generated by Django 3.1.4 on 2020-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='check',
            field=models.BooleanField(),
        ),
    ]
